name: "DAST OWASP ZAP"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write
  security-events: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run OWASP Juice Shop in Docker
        run: |
          docker run -d -p 3000:3000 bkimminich/juice-shop
          sleep 15  # Attendre que le service démarre

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:3000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -J zap-report.json'

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: zap-report.json
        if: always()
