name: "SCA using Snyk"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write
  security-events: write

jobs:
  security_testing:
    name: Security Testing
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Run Snyk to check for vulnerabilities
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          npm install -g snyk
          snyk auth $SNYK_TOKEN
          snyk test --json > snyk-results.json || true
          cat snyk-results.json
      
      - name: Verify JSON file exists
        run: |
          if [ -f snyk-results.json ]; then
            echo "✅ snyk-results.json trouvé"
            ls -lh snyk-results.json
          else
            echo "❌ snyk-results.json non trouvé"
            echo "{\"error\": \"Aucun résultat généré\"}" > snyk-results.json
          fi
      
      - name: Upload Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results
          path: snyk-results.json
        if: always()
